# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1261, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_fp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_fp.setObjectName("le_fp")
        self.horizontalLayout.addWidget(self.le_fp)
        self.btn_load = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_load.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_load.setFont(font)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout.addWidget(self.btn_load)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 1261, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tb_all_report = QtWidgets.QWidget()
        self.tb_all_report.setObjectName("tb_all_report")
        self.tbv_all_report = QtWidgets.QTableView(self.tb_all_report)
        self.tbv_all_report.setGeometry(QtCore.QRect(0, 10, 1261, 571))
        self.tbv_all_report.setObjectName("tbv_all_report")
        self.tabWidget.addTab(self.tb_all_report, "")
        self.tb_check = QtWidgets.QWidget()
        self.tb_check.setObjectName("tb_check")
        self.gb_check = QtWidgets.QGroupBox(self.tb_check)
        self.gb_check.setGeometry(QtCore.QRect(0, 0, 630, 581))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gb_check.setFont(font)
        self.gb_check.setObjectName("gb_check")
        self.tbv_check = QtWidgets.QTableView(self.gb_check)
        self.tbv_check.setGeometry(QtCore.QRect(10, 30, 611, 541))
        self.tbv_check.setObjectName("tbv_check")
        self.gb_non_check = QtWidgets.QGroupBox(self.tb_check)
        self.gb_non_check.setGeometry(QtCore.QRect(640, 0, 621, 581))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gb_non_check.setFont(font)
        self.gb_non_check.setObjectName("gb_non_check")
        self.tbv_non_check = QtWidgets.QTableView(self.gb_non_check)
        self.tbv_non_check.setGeometry(QtCore.QRect(10, 30, 601, 541))
        self.tbv_non_check.setObjectName("tbv_non_check")
        self.tabWidget.addTab(self.tb_check, "")
        self.tb_doctor = QtWidgets.QWidget()
        self.tb_doctor.setObjectName("tb_doctor")
        self.tbv_doctor_m_report = QtWidgets.QTableView(self.tb_doctor)
        self.tbv_doctor_m_report.setGeometry(QtCore.QRect(10, 10, 1251, 501))
        self.tbv_doctor_m_report.setSortingEnabled(True)
        self.tbv_doctor_m_report.setObjectName("tbv_doctor_m_report")
        self.tbw_doctor = QtWidgets.QTableWidget(self.tb_doctor)
        self.tbw_doctor.setEnabled(True)
        self.tbw_doctor.setGeometry(QtCore.QRect(10, 520, 1251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tbw_doctor.setFont(font)
        self.tbw_doctor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbw_doctor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbw_doctor.setDragDropOverwriteMode(False)
        self.tbw_doctor.setShowGrid(True)
        self.tbw_doctor.setGridStyle(QtCore.Qt.DashLine)
        self.tbw_doctor.setObjectName("tbw_doctor")
        self.tbw_doctor.setColumnCount(12)
        self.tbw_doctor.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_doctor.setHorizontalHeaderItem(11, item)
        self.tbw_doctor.horizontalHeader().setCascadingSectionResizes(False)
        self.tabWidget.addTab(self.tb_doctor, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_load.setText(_translate("MainWindow", "讀取報表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_all_report), _translate("MainWindow", "總報表"))
        self.gb_check.setTitle(_translate("MainWindow", "核實人數"))
        self.gb_non_check.setTitle(_translate("MainWindow", "非核實人數"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_check), _translate("MainWindow", "報表檢驗"))
        item = self.tbw_doctor.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "總計"))
        item = self.tbw_doctor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "病人總數"))
        item = self.tbw_doctor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "掛號費"))
        item = self.tbw_doctor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "自付費"))
        item = self.tbw_doctor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "自費"))
        item = self.tbw_doctor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "押金"))
        item = self.tbw_doctor.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "藥自付"))
        item = self.tbw_doctor.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "欠款"))
        item = self.tbw_doctor.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "還款"))
        item = self.tbw_doctor.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "核實人數"))
        item = self.tbw_doctor.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "時數"))
        item = self.tbw_doctor.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "醫師診費"))
        item = self.tbw_doctor.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "醫師薪水"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_doctor), _translate("MainWindow", "醫生薪資計算"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

